name: Deploying content to the Lab site

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy file
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        env:
          FTP_SERVER: home562576484.1and1-data.host
          FTP_USERNAME: ${{secrets.ftp_username}}
          FTP_PASSWORD: ${{secrets.ftp_password}}
          local-dir: '.'
          server-dir: '/IS436/lab5'
